// ============================================================================
// FMP industry → Damodaran industry. FMP profiles use Morningstar-style
// industry names (159 of them, Oct 2026); Damodaran's datasets use his own 94.
// Drafted by hand from the two lists; where an FMP industry straddles two of
// his (exchanges and rating agencies, distributors, refiners), it goes to the
// one whose economics fit most of its members. Edit freely — a wrong match
// only changes the yardstick, never the company's own numbers.
// An FMP industry not listed here falls back to the market as a whole.
// ============================================================================
export const FMP_TO_DAMODARAN = {
  "Advertising Agencies": "Advertising",
  "Aerospace & Defense": "Aerospace/Defense",
  "Agricultural - Commodities/Milling": "Farming/Agriculture",
  "Agricultural - Machinery": "Machinery",
  "Agricultural Farm Products": "Farming/Agriculture",
  "Agricultural Inputs": "Chemical (Basic)",
  "Airlines, Airports & Air Services": "Air Transport",
  "Aluminum": "Metals & Mining",
  "Apparel - Footwear & Accessories": "Shoe",
  "Apparel - Manufacturers": "Apparel",
  "Apparel - Retail": "Retail (Special Lines)",
  "Asset Management": "Investments & Asset Management",
  "Asset Management - Bonds": "Investments & Asset Management",
  "Asset Management - Cryptocurrency": "Investments & Asset Management",
  "Asset Management - Global": "Investments & Asset Management",
  "Asset Management - Income": "Investments & Asset Management",
  "Asset Management - Leveraged": "Investments & Asset Management",
  "Auto - Dealerships": "Retail (Automotive)",
  "Auto - Manufacturers": "Auto & Truck",
  "Auto - Parts": "Auto Parts",
  "Auto - Recreational Vehicles": "Recreation",
  "Banks": "Banks (Regional)",
  "Banks - Diversified": "Bank (Money Center)",
  "Banks - Regional": "Banks (Regional)",
  "Beverages - Alcoholic": "Beverage (Alcoholic)",
  "Beverages - Non-Alcoholic": "Beverage (Soft)",
  "Beverages - Wineries & Distilleries": "Beverage (Alcoholic)",
  "Biotechnology": "Drugs (Biotechnology)",
  "Broadcasting": "Broadcasting",
  "Business Equipment & Supplies": "Office Equipment & Services",
  "Chemicals": "Chemical (Basic)",
  "Chemicals - Specialty": "Chemical (Specialty)",
  "Coal": "Coal & Related Energy",
  "Communication Equipment": "Telecom. Equipment",
  "Computer Hardware": "Computers/Peripherals",
  "Conglomerates": "Diversified",
  "Construction": "Engineering/Construction",
  "Construction Materials": "Construction Supplies",
  "Consulting Services": "Business & Consumer Services",
  "Consumer Electronics": "Electronics (Consumer & Office)",
  "Copper": "Metals & Mining",
  "Department Stores": "Retail (General)",
  "Discount Stores": "Retail (General)",
  "Diversified Utilities": "Utility (General)",
  "Drug Manufacturers - General": "Drugs (Pharmaceutical)",
  "Drug Manufacturers - Specialty & Generic": "Drugs (Pharmaceutical)",
  "Education & Training Services": "Education",
  "Electrical Equipment & Parts": "Electrical Equipment",
  "Electronic Gaming & Multimedia": "Software (Entertainment)",
  "Engineering & Construction": "Engineering/Construction",
  "Entertainment": "Entertainment",
  "Environmental Services": "Environmental & Waste Services",
  "Financial - Capital Markets": "Brokerage & Investment Banking",
  "Financial - Conglomerates": "Financial Svcs. (Non-bank & Insurance)",
  "Financial - Credit Services": "Financial Svcs. (Non-bank & Insurance)",
  "Financial - Data & Stock Exchanges": "Information Services",
  "Financial - Diversified": "Financial Svcs. (Non-bank & Insurance)",
  "Financial - Mortgages": "Financial Svcs. (Non-bank & Insurance)",
  "Food Confectioners": "Food Processing",
  "Food Distribution": "Food Wholesalers",
  "Furnishings, Fixtures & Appliances": "Furn/Home Furnishings",
  "Gambling, Resorts & Casinos": "Hotel/Gaming",
  "General Transportation": "Transportation",
  "General Utilities": "Utility (General)",
  "Gold": "Precious Metals",
  "Grocery Stores": "Retail (Grocery and Food)",
  "Hardware, Equipment & Parts": "Electronics (General)",
  "Home Improvement": "Retail (Building Supply)",
  "Household & Personal Products": "Household Products",
  "Independent Power Producers": "Power",
  "Industrial - Capital Goods": "Machinery",
  "Industrial - Distribution": "Retail (Distributors)",
  "Industrial - Infrastructure Operations": "Engineering/Construction",
  "Industrial - Machinery": "Machinery",
  "Industrial - Pollution & Treatment Controls": "Environmental & Waste Services",
  "Industrial - Specialties": "Machinery",
  "Industrial Materials": "Metals & Mining",
  "Information Technology Services": "Computer Services",
  "Insurance - Brokers": "Insurance (General)",
  "Insurance - Diversified": "Insurance (General)",
  "Insurance - Life": "Insurance (Life)",
  "Insurance - Property & Casualty": "Insurance (Prop/Cas.)",
  "Insurance - Reinsurance": "Reinsurance",
  "Insurance - Specialty": "Insurance (General)",
  "Integrated Freight & Logistics": "Transportation",
  "Internet Content & Information": "Software (Internet)",
  "Investment - Banking & Investment Services": "Brokerage & Investment Banking",
  "Leisure": "Recreation",
  "Luxury Goods": "Apparel",
  "Manufacturing - Metal Fabrication": "Machinery",
  "Manufacturing - Miscellaneous": "Diversified",
  "Manufacturing - Textiles": "Apparel",
  "Manufacturing - Tools & Accessories": "Machinery",
  "Marine Shipping": "Shipbuilding & Marine",
  "Media & Entertainment": "Entertainment",
  "Medical - Care Facilities": "Hospitals/Healthcare Facilities",
  "Medical - Devices": "Healthcare Products",
  "Medical - Diagnostics & Research": "Healthcare Products",
  "Medical - Distribution": "Healthcare Support Services",
  "Medical - Equipment & Services": "Healthcare Products",
  "Medical - Healthcare Information Services": "Heathcare Information and Technology",
  "Medical - Healthcare Plans": "Healthcare Support Services",
  "Medical - Instruments & Supplies": "Healthcare Products",
  "Medical - Pharmaceuticals": "Drugs (Pharmaceutical)",
  "Medical - Specialties": "Healthcare Products",
  "Oil & Gas Drilling": "Oilfield Svcs/Equip.",
  "Oil & Gas Energy": "Oil/Gas (Production and Exploration)",
  "Oil & Gas Equipment & Services": "Oilfield Svcs/Equip.",
  "Oil & Gas Exploration & Production": "Oil/Gas (Production and Exploration)",
  "Oil & Gas Integrated": "Oil/Gas (Integrated)",
  "Oil & Gas Midstream": "Oil/Gas Distribution",
  "Oil & Gas Refining & Marketing": "Oil/Gas (Integrated)",
  "Other Precious Metals": "Precious Metals",
  "Packaged Foods": "Food Processing",
  "Packaging & Containers": "Packaging & Container",
  "Paper, Lumber & Forest Products": "Paper/Forest Products",
  "Personal Products & Services": "Business & Consumer Services",
  "Publishing": "Publishing & Newspapers",
  "REIT - Diversified": "R.E.I.T.",
  "REIT - Healthcare Facilities": "R.E.I.T.",
  "REIT - Hotel & Motel": "R.E.I.T.",
  "REIT - Industrial": "R.E.I.T.",
  "REIT - Mortgage": "R.E.I.T.",
  "REIT - Office": "R.E.I.T.",
  "REIT - Residential": "R.E.I.T.",
  "REIT - Retail": "Retail (REITs)",
  "REIT - Specialty": "R.E.I.T.",
  "Railroads": "Transportation (Railroads)",
  "Real Estate - Development": "Real Estate (Development)",
  "Real Estate - Diversified": "Real Estate (General/Diversified)",
  "Real Estate - General": "Real Estate (General/Diversified)",
  "Real Estate - Services": "Real Estate (Operations & Services)",
  "Regulated Electric": "Utility (General)",
  "Regulated Gas": "Utility (General)",
  "Regulated Water": "Utility (Water)",
  "Renewable Utilities": "Green & Renewable Energy",
  "Rental & Leasing Services": "Business & Consumer Services",
  "Residential Construction": "Homebuilding",
  "Restaurants": "Restaurant/Dining",
  "Security & Protection Services": "Business & Consumer Services",
  "Semiconductors": "Semiconductor",
  "Silver": "Precious Metals",
  "Software - Application": "Software (System & Application)",
  "Software - Infrastructure": "Software (System & Application)",
  "Software - Services": "Computer Services",
  "Solar": "Green & Renewable Energy",
  "Specialty Business Services": "Business & Consumer Services",
  "Specialty Retail": "Retail (Special Lines)",
  "Staffing & Employment Services": "Business & Consumer Services",
  "Steel": "Steel",
  "Technology Distributors": "Retail (Distributors)",
  "Telecommunications Services": "Telecom. Services",
  "Tobacco": "Tobacco",
  "Travel Lodging": "Hotel/Gaming",
  "Travel Services": "Recreation",
  "Trucking": "Trucking",
  "Uranium": "Metals & Mining",
  "Waste Management": "Environmental & Waste Services",
};

// Companies whose FMP industry lumps them with a different business than
// Damodaran's closest match: chip-equipment makers sit in FMP "Semiconductors",
// cable and wireless carriers in "Telecommunications Services", HVAC and
// building-products makers in machinery or construction materials.
export const SYMBOL_OVERRIDES = {
  AMAT: "Semiconductor Equip", LRCX: "Semiconductor Equip", KLAC: "Semiconductor Equip", TER: "Semiconductor Equip", ASML: "Semiconductor Equip",
  CMCSA: "Cable TV", CHTR: "Cable TV",
  TMUS: "Telecom (Wireless)",
  MAS: "Building Materials", JCI: "Building Materials", CARR: "Building Materials", TT: "Building Materials", OC: "Building Materials",
  DD: "Chemical (Diversified)",
  GT: "Rubber& Tires",
};
