import React,{useMemo,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import {annualRecords,trailingRecord,quarterRecords,periodMetrics,growthRate,currentValuation,sheetWarnings,numeric,ratio,difference,isBankOrInsurer} from '../../lib/stockResearch.js';
import {industryOf} from '../../lib/costOfCapital.js';
import './StockResearchSheet.css';

const num=(v,dp=1)=>numeric(v)===null?'—':Number(v).toLocaleString('en-US',{minimumFractionDigits:dp,maximumFractionDigits:dp});
const pct=v=>numeric(v)===null?'—':num(v*100)+'%';
const multiple=v=>numeric(v)===null?'—':num(v)+'×';
const compact=v=>numeric(v)===null?'—':Math.abs(v)>=1e12?num(v/1e12,2)+'T':Math.abs(v)>=1e9?num(v/1e9,2)+'B':Math.abs(v)>=1e6?num(v/1e6,1)+'M':num(v,0);
const format=(value,type)=>type==='percent'?pct(value):type==='multiple'?multiple(value):type==='millions'?num(numeric(value)===null?null:value/1e6,0):num(value,2);
const ROWS=[
 {title:'Per-share record',rows:[['Revenue / diluted share','revenuePerShare','perShare'],['Diluted earnings / share','eps','perShare'],['Free cash flow / diluted share','fcfPerShare','perShare'],['Dividends paid / diluted share','dividendsPerShare','perShare'],['Diluted average shares (m)','shares','millions']]},
 {title:'Business performance',rows:[['Revenue','revenue','millions'],['Gross margin','grossMargin','percent'],['Operating margin','operatingMargin','percent'],['Net income','netIncome','millions'],['Net margin','netMargin','percent'],['Operating cash flow','cfo','millions'],['Capital expenditure','capex','millions'],['Free cash flow','fcf','millions'],['FCF / net income','cashConversion','percent']]},
 {title:'Capital and returns',rows:[['Cash & short-term investments','liquidAssets','millions'],['Total debt, including leases','debt','millions'],['Shareholders’ equity','equity','millions'],['Return on invested capital','roic','percent'],['Return on equity','roe','percent'],['Share repurchases','repurchases','millions'],['Stock compensation / revenue','sbcSales','percent']]},
];

function QuarterTable({title,rows,metric,type,annual}) {
  const years=[...new Set(rows.map(q=>q.year))].slice(-3);
  return <section><h2>{title}</h2><div className="sheet-scroll"><table className="sheet-small-table"><thead><tr><th>Fiscal year</th>{['Q1','Q2','Q3','Q4','FY'].map(q=><th key={q}>{q}</th>)}</tr></thead><tbody>{years.map(y=><tr key={y}><th>{y}</th>{['Q1','Q2','Q3','Q4'].map(q=>{const p=rows.find(r=>r.year===y&&r.period===q);return <td key={q} title={p?.date?('Period ended '+p.date):'Not available'}>{format(periodMetrics(p)[metric],type)}</td>;})}<td>{format(periodMetrics(annual.find(r=>r.year===y))[metric],type)}</td></tr>)}</tbody></table></div></section>;
}

export default function StockResearchSheet({data}) {
  const [years,setYears]=useState(10),[chartYears,setChartYears]=useState(5);
  const annual=useMemo(()=>annualRecords(data),[data]),ttm=useMemo(()=>trailingRecord(data),[data]);
  const quarter=useMemo(()=>quarterRecords(data),[data]),latest=ttm||annual.at(-1),lastFY=annual.at(-1);
  const current=periodMetrics(latest),valuation=currentValuation(data,latest),prof=data.prof||{},quote=data.quote||{};
  const financial=isBankOrInsurer(data);
  // Damodaran's U.S. industry average beside each headline figure
  const industry=industryOf(data),ir=industry.row||{};
  const vsIndustry=(text,value,format)=>numeric(value)===null?text:text+' · industry '+format(value);
  const shown=annual.slice(-years),columns=[...shown,...(ttm?[ttm]:[])],warnings=sheetWarnings(data,annual,ttm);
  const currency=latest?.currency||prof.currency||'Currency unavailable',quoteCurrency=prof.currency||'';
  const priceDate=numeric(quote.timestamp)!==null?new Date(Number(quote.timestamp)*1000).toISOString().slice(0,10):null;
  const allPrices=(data.longHist||data.hist||[]).filter(p=>p.date&&numeric(p.adjClose??p.close)>0).sort((a,b)=>a.date.localeCompare(b.date));
  const lastPriceDate=allPrices.at(-1)?.date,cutoff=lastPriceDate?new Date(Date.parse(lastPriceDate)-chartYears*365.25*86400000).toISOString().slice(0,10):'';
  const priceRows=allPrices.filter(p=>p.date>=cutoff).map(p=>({date:p.date,price:numeric(p.adjClose??p.close)}));
  const change=numeric(quote.changePercentage??prof.changePercentage),revenueGrowth=growthRate(annual,'revenue',5),fcfGrowth=growthRate(annual,'fcfPerShare',5);
  const cashAfterDebt=difference(current.liquidAssets,current.debt);
  const safeWebsite=/^https?:\/\//i.test(prof.website||'')?prof.website:null;
  const descriptions=(prof.description||'').match(/[^.!?]+[.!?]+(?:\s|$)/g);
  const introduction=descriptions?.slice(0,2).join(' ').trim()||prof.description;
  return <article className="stock-sheet" aria-label={data.symbol+' company research sheet'}>
    <header className="sheet-masthead"><div className="sheet-identity"><div className="sheet-kicker">{data.symbol} / {prof.exchange||prof.exchangeShortName||'Listed equity'}</div><h1>{prof.companyName||data.symbol}</h1><p>{[prof.sector,prof.industry].filter(Boolean).join(' / ')}</p></div><div className="sheet-price">{num(data.price,2)} {quoteCurrency}<small>{change===null?'Change unavailable':(change>=0?'+':'')+num(change,2)+'%'} / quote {priceDate||'date unavailable'}</small></div></header>
    <div className="sheet-valuation">{[
      ['Market value',compact(valuation.cap),quoteCurrency],
      ['Price / earnings',multiple(valuation.pe),vsIndustry(ttm?'Trailing diluted EPS':'Latest fiscal-year EPS',ir.peTrail,multiple)],
      financial?['Price / book',multiple(valuation.priceBook),vsIndustry('Market value / shareholders’ equity',ir.pbv,multiple)]:['Free cash flow yield',pct(valuation.fcfYield),ttm?'Trailing FCF / market value':'Latest FY FCF / market value'],
      ['Dividend cash yield',pct(valuation.dividendYield),ttm?'Trailing common cash dividends':'Latest FY common cash dividends'],
      [financial?'Return on equity':'Return on invested capital',pct(periodMetrics(lastFY)[financial?'roe':'roic']),vsIndustry('FY '+(lastFY?.year||'—')+' / provider definition',financial?ir.roe:ir.roc,pct)],
    ].map(([label,value,note])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div>
    <div className="sheet-top"><section><div className="sheet-heading"><h2>Price record</h2><div className="sheet-actions">{[1,3,5].map(y=><button key={y} onClick={()=>setChartYears(y)} aria-pressed={chartYears===y}>{y}Y</button>)}</div></div>
      {priceRows.length>1?<div className="sheet-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={priceRows} margin={{top:8,right:10,bottom:5,left:0}}><CartesianGrid vertical={false} stroke="#bdc7cf"/><XAxis dataKey="date" tickFormatter={d=>d.slice(0,4)} minTickGap={70} tick={{fontSize:12}} tickLine={false}/><YAxis domain={['auto','auto']} tickFormatter={v=>num(v,0)} orientation="right" tick={{fontSize:12}} tickLine={false} width={50}/><Tooltip labelFormatter={d=>d} formatter={v=>[num(v,2)+' '+quoteCurrency,'Price']} contentStyle={{background:'#fff',color:'#1c2a37',border:'1px solid #bec7ce',fontSize:13}} itemStyle={{color:'#215784'}}/><Line dataKey="price" stroke="#215784" strokeWidth={1.6} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>:<p className="sheet-note">Price history is unavailable.</p>}
      <p className="sheet-note">{priceRows[0]?.date||'—'} to {priceRows.at(-1)?.date||'—'} / provider price history; adjusted close where supplied. This is a price series, not a total-return comparison.</p>
    </section><section className="sheet-business"><h2>The business</h2><p>{introduction||'Business description unavailable.'}</p>{prof.description&&prof.description!==introduction&&<details><summary>Full business description</summary><p>{prof.description}</p></details>}<dl><dt>Headquarters</dt><dd>{[prof.city,prof.state,prof.country].filter(Boolean).join(', ')||'—'}</dd><dt>Employees</dt><dd>{num(prof.fullTimeEmployees,0)}</dd><dt>Latest annual period</dt><dd>{lastFY?.date||'—'}</dd><dt>Latest income quarter</dt><dd>{quarter.at(-1)?.date||'—'}</dd><dt>52-week range</dt><dd>{num(quote.yearLow,2)}–{num(quote.yearHigh,2)}</dd></dl>{safeWebsite&&<a className="sheet-link" href={safeWebsite} target="_blank" rel="noreferrer">Company website ↗</a>}</section></div>
    <section><div className="sheet-heading"><h2>Financial history</h2><div className="sheet-actions" aria-label="Years of financial history">{[5,10,20].map(y=><button key={y} onClick={()=>setYears(y)} aria-pressed={years===y}>{y} years</button>)}</div></div><p className="sheet-note">{currency} millions, except per-share amounts, percentages and ratios. Years are fiscal years; period-end dates appear below each heading. {ttm?'TTM flows end '+ttm.date+'; TTM balance-sheet values are the snapshot at that date.':'Trailing figures unavailable.'}</p>
      <div className="sheet-scroll" tabIndex={0} aria-label="Scrollable financial history"><table className="sheet-financials"><thead><tr><th>Fiscal record</th>{columns.map(p=><th key={p.period+'-'+p.date+'-'+p.currency} className={p.period==='TTM'?'sheet-trailing':''}>{p.year}<small>{p.date}</small>{p.currency!==currency&&<small>{p.currency||'Unknown currency'}</small>}</th>)}</tr></thead><tbody>{ROWS.map(group=><React.Fragment key={group.title}><tr className="sheet-group"><th colSpan={columns.length+1}>{group.title}</th></tr>{group.rows.map(([label,key,type])=><tr key={key}><th scope="row">{label}</th>{columns.map(p=>{const value=periodMetrics(p)[key];return <td key={p.period+'-'+p.date+'-'+p.currency} className={p.period==='TTM'?'sheet-trailing':''} data-negative={value!==null&&value<0}>{format(value,type)}</td>;})}</tr>)}</React.Fragment>)}</tbody></table></div>
      <p className="sheet-note">Per-share cash figures use diluted weighted-average shares; dividends per share represent cash paid divided by that share count. TTM EPS sums four reported quarterly figures, and TTM cash per share uses their mean diluted share count. Historical provider data may be restated. No second split adjustment is applied.</p>
    </section>
    <div className="sheet-bottom"><section><h2>Capital structure & liquidity</h2><p className="sheet-note">Snapshot {latest?.b?.date||'unavailable'} / {currency} millions</p><table className="sheet-small-table"><tbody>{[
      ['Cash & equivalents',current.cash],['Short-term investments',numeric(latest?.b?.shortTermInvestments)],['Debt incl. leases',current.debt],['Lease obligations',numeric(latest?.b?.capitalLeaseObligations)],['Cash-only net debt',current.netDebt],['Cash + investments less debt',cashAfterDebt],['Shareholders equity',current.equity],['Working capital',current.workingCapital],
    ].map(([label,value])=><tr key={label}><th>{label}</th><td>{format(value,'millions')}</td></tr>)}</tbody></table><p className="sheet-note">Cash-only net debt excludes short-term investments. Positive cash + investments less debt indicates liquid assets exceed reported debt. Balance-sheet amounts are not summed across quarters. {financial?'Customer and regulatory obligations mean these balances are not distributable excess cash.':''}</p></section>
    <section><h2>Annual growth record</h2><p className="sheet-note">Compound rates through FY {lastFY?.year||'—'}</p><div className="sheet-scroll"><table className="sheet-small-table"><thead><tr><th>Metric</th>{[10,5,1].map(y=><th key={y}>{y}Y</th>)}</tr></thead><tbody>{[['Revenue','revenue'],['Diluted EPS','eps'],['FCF / diluted share','fcfPerShare'],['Share count','shares'],['Shareholders equity','equity']].map(([label,key])=><tr key={key}><th>{label}</th>{[10,5,1].map(y=><td key={y}>{pct(growthRate(annual,key,y))}</td>)}</tr>)}</tbody></table></div><p className="sheet-note">Requires matching fiscal years, comparable currency and positive endpoints. A dash avoids presenting a loss-to-profit transition as a compound growth rate.</p></section>
    <section><h2>Fundamental checkpoints</h2><div className="sheet-observation"><h3>Growth per share</h3><p>Five-year revenue growth: <strong>{pct(revenueGrowth)}</strong>. FCF per diluted share: <strong>{pct(fcfGrowth)}</strong>.</p></div><div className="sheet-observation"><h3>{financial?'Balance-sheet capital':'Earnings into cash'}</h3>{financial?<p>Shareholders’ equity is <strong>{pct(ratio(current.equity,numeric(latest?.b?.totalAssets)))}</strong> of reported assets. This is an accounting ratio, not a regulatory capital ratio.</p>:<p>{ttm?'Trailing':'Latest annual'} FCF is <strong>{pct(current.cashConversion)}</strong> of net income; capital spending is <strong>{pct(ratio(current.capex,current.revenue))}</strong> of sales.</p>}</div><div className="sheet-observation"><h3>Capital returned</h3><p>{ttm?'Trailing':'Latest annual'} repurchases: <strong>{compact(current.repurchases)} {currency}</strong>. Common cash dividends: <strong>{compact(current.dividends)} {currency}</strong>.</p></div><p className="sheet-note">These comparisons describe reported economics. Acquisition spending, stock compensation and working-capital changes can affect their interpretation.</p></section></div>
    <div className="sheet-quarterly"><QuarterTable title={'Quarterly revenue / '+currency+' millions'} rows={quarter} annual={annual} metric="revenue" type="millions"/><QuarterTable title={'Quarterly diluted EPS / '+currency} rows={quarter} annual={annual} metric="eps" type="perShare"/></div>
    <footer className="sheet-source">{warnings.map(w=><p className="sheet-warning" key={w}>{w}</p>)}<p className="sheet-note">Source: Financial Modeling Prep standardized statements, financial metrics, profile and market quotes / retrieved {data.retrievedAt?.slice(0,10)||'date unavailable'}. Annual ROIC and ROE use provider definitions; trailing returns on capital remain blank. Figures are not filing-audited here. Missing values are shown as —.</p>
      <details><summary>Sources and calculation notes</summary><p className="sheet-note">Income, cash-flow and balance-sheet records are joined on fiscal period, exact end date and reporting currency. Free cash flow is the provider’s operating cash flow less capital spending. Repurchases, dividends and capex display positive cash outflows. FCF yield and dividend cash yield divide reported cash amounts by current market capitalization; they are not forecasts. TTM figures require four consecutive quarters. Per-share valuation is withheld for unverified ADR ratios and mismatched currencies.</p><div className="sheet-scroll"><table className="sheet-small-table"><thead><tr><th>Source</th><th>Available rows</th><th>Status</th></tr></thead><tbody>{(data.sources||[]).map(s=><tr key={s.id}><td><a href="https://site.financialmodelingprep.com/developer/docs" target="_blank" rel="noreferrer">{s.label}</a></td><td>{s.rows}</td><td>{s.status}</td></tr>)}</tbody></table></div>{prof.cik&&<p className="sheet-note"><a href={'https://www.sec.gov/edgar/browse/?CIK='+encodeURIComponent(prof.cik)+'&owner=exclude'} target="_blank" rel="noreferrer">Company filings on SEC EDGAR ↗</a></p>}</details>
    </footer>
  </article>;
}
